### PR TITLE
[WIP] scrapy-streaming examples

### PR DESCRIPTION
**Pull request by nrbrd**
## PR Overview

I'll be updating this branch with scrapy-streaming examples, while implementing them in the project development.
### Examples
1. **check_response_status** - This spider open a list of domains and check which domain is returning a valid status.
2. **extract_dmoz_links** - This example is covered in the quickstart section. It gets a list of websites with Python related articles
3.  **request_image** - This demo shows how to download binary data using scrapy-streaming.
4.  **request_utf8** - How to crawl webpages with utf-8 data.

| Example | Python | R | Java | More languages ... |
| --- | --- | --- | --- | --- |
| 1 | :white_check_mark: | :white_check_mark: | :white_check_mark: | x |
| 2 | :white_check_mark: | :white_check_mark: | :white_check_mark: | x |
| 3 | :white_check_mark: | :white_check_mark: | :white_check_mark: | x |
| 4 | :white_check_mark: | x | :white_check_mark: | x |

### CODE REVIEW

**Comment by nrbrd** [comment]
This folder will contains as much as possible practical examples of scrapy-streaming, and some usage tips. It's ok to have spiders using these popular websites, such as github here ?

(I removed the extract_github_data example in this PR from quickstart section, so I'd like to confirm if I can keep it here)
cc: @eLRuLL , @redapple 

-- edited:
Currently, examples [3] and [4] are using a github spider.

**Comment by eLRuLL** [comment]
according to the [robots.txt](https://github.com/robots.txt) file it is disallowing everything inside github for normal user-agents, maybe we could download those responses once? and make some examples with files, what do you think @redapple ?

**Comment by redapple** [comment]
@eLRuLL , I would not include GitHub, especially since they have a very comprehensive API.
@stummjr is working on scrapy (or scrapinghub) maintainted live website to build scraping example against. Not sure of the status of this being live yet though.

**Comment by stummjr** [comment]
@redapple it's live on http://dev.scrapinghub.com/~valdir but it's gonna be moved to a proper place soon.

**Comment by eLRuLL** [comment]
@aron-bordin please remove the Github examples.

**Pull request merged**
